[package]
name = "eddiethedean/dpcs"
version = "0.10.0"
description = "DPCS WebAssembly toolkit (wasm-bindgen)"
license = "Apache-2.0 OR MIT"
readme = "README.md"
repository = "https://github.com/eddiethedean/dpcs"

[[module]]
name = "dpcs"
source = "pkg/dpcs_bg.wasm"
abi = "none"
